pipeline{
    agent any
    stages{
        stage('Checkout'){
            steps{
                echo 'Checking out code...'
            }
        }
        stage('Build docker image'){
            steps{
                echo 'Building...'
            }
        }
        stage('Test'){
            steps{
                echo 'Testing...'
            }
        }
        stage('Deploy'){
            steps{
                echo 'Deploying...'
            }
        }
    }
}

