pipeline{
    agent any
    stages{
        stage('Checkout'){
            steps{ Checkout scm}
        }
        stage('Build docker image'){
            steps{
                sh "docker build -t project1:${BUILD_NUMBER} ."
            }
        }
        stage('Test'){
            steps{
                echo 'Testing...'
            }
        }
        stage('Deploy'){
            steps{
                sh "kubectl apply -f k8s/deployment.yaml"
            }
        }
    }
}

